# setup repo
- name: prepare for apt_repository
  apt: pkg=python-software-properties update-cache=yes state=present

- name: add nginx ppa
  apt_repository: repo=ppa:nginx/stable state=present

- name: add redis ppa
  apt_repository: repo=ppa:chris-lea/redis-server state=present

# install packages
- name: install ubuntu packages
  apt: pkg=$item state=present
  with_items:
    - nginx
    - python-pip
    - build-essential
    - python-dev
    - libev-dev
    - cython
    - git-core
    - redis-server
    - supervisor

- name: update pip
  pip: name=pip state=latest

- name: install global python packages
  pip: name=$item state=present
  with_items:
    - virtualenv
    - uwsgi
