# setup repo
- name: prepare for apt_repository
  apt: pkg=python-software-properties update-cache=yes state=present

- name: add nginx ppa
  apt_repository: repo=ppa:nginx/stable state=present

- name: add redis ppa
  apt_repository: repo=ppa:chris-lea/redis-server state=present

# install packages
- name: install ubuntu packages
  apt: pkg=$item state=present
  with_items:
    - nginx
    - uwsgi
    - uwsgi-plugin-python
    - python-pip
    - build-essential
    - git-core
    - redis-server

- name: install python packages
  pip: name=$item state=present
  with_items:
    - pip
    - virtualenv
