# uwsgi app
- name: create directory for app
  file: path=${webapps_dir}/${app_name} state=directory

- name: deploy code from repository
  git: repo=$repo_url dest=${webapps_dir}/${app_name}/src remote=$repo_remote version=$repo_version

- name: install dependencies into virtualenv
  pip: requirements=${webapps_dir}/${app_name}/src/requirements.txt virtualenv=${webapps_dir}/${app_name}/venv state=present

- name: symlink uwsgi app
  file: src=/etc/uwsgi/apps-available/${app_name}.ini dest=/etc/uwsgi/apps-enabled/${app_name}.ini state=link

- name: update uwsgi app
  template: src=templates/uwsgi_app.ini dest=/etc/uwsgi/apps-available/${app_name}.ini
  notify:
    - restart uwsgi

# nginx
- name: remove default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: symlink nginx site
  file: src=/etc/nginx/sites-available/${app_url}.conf dest=/etc/nginx/sites-enabled/${app_url}.conf state=link

- name: update nginx site
  template: src=templates/nginx_site.conf dest=/etc/nginx/sites-available/${app_url}.conf
  notify:
    - restart nginx
